pg/urls.py
from django.conf.urls import url
from pg.views import home, PortfolioView, resume, blog, contact

app_name = 'pg'
urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^portfolio/$', PortfolioView.as_view(), name='portfolio'),
    url(r'^resume/$', resume, name='resume'),
    url(r'^blog/$', blog, name='blog'),
    url(r'^contact/$', contact, name='contact')
]

photograpy/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pg.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

pg/models.py
from django.db import models

# Create your models here.

class Banner(models.Model):
	title = models.CharField(max_length = 50, blank = False)
	desc = models.TextField(blank = True)
	image = models.ImageField('media', blank = False)
	status = models.BooleanField()
	status.default = False

class Category(models.Model):
	title = models.CharField(max_length = 100, blank = False, unique = True)
	image = models.ImageField('media/category', blank = False, upload_to = 'category')
	status = models.BooleanField()
	status.default = False

	def __str__(self):
		return self.title

class Portfolio(models.Model):
	cat_id = models.ForeignKey(
		'pg.Category',
		on_delete=models.CASCADE
	)
	image = models.ImageField('media/portfolio', blank = False, upload_to = 'portfolio')
	status = models.BooleanField()
	status.default = True
	created_date = models.DateField()
	created_date.null = True

class Blog(models.Model):
	title = models.CharField(max_length = 100, blank = False)
	desc = models.TextField(blank = True)
	image = models.ImageField('media/blog', blank = False, upload_to = 'blog')
	status = models.BooleanField()
	status.default = False
	created_date = models.DateField()
	created_date.null = True

class Contact(models.Model):
	name = models.CharField(max_length = 100, blank = False)
	email = models.EmailField(max_length = 100, blank = False)
	phone = models.PositiveBigIntegerField(blank = False)
	message = models.TextField(blank = False)
	created_date = models.PositiveIntegerField()

pg/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from pg.models import Banner, Category, Portfolio, Blog
from pg.services.ser import mainService
from django.views import generic

# Create your views here.

def home(request):
	return render(request, 'home.html', {
		'banner' : Banner.objects.filter(status = 1),
		'category' : Category.objects.filter(status = 1),
		'random' : Portfolio.objects.only('image').filter(status = 1).order_by('-created_date')[:10]
	})

class PortfolioView(generic.ListView):
	template_name = 'portfolio.html'
	context_object_name = 'portfolio'

	def get_queryset(self):
		return mainService(1).getPortfolio()

def resume(request):
	return render(request, 'resume.html')

def blog(request):
	return render(request, 'blog.html', {
		'blog' : Blog.objects.filter(status = 1).order_by('-created_date') 
	})

def contact(request):
	if request.method == "GET":
		return render(request, 'contact.html', {'err':'', 'postdata':''})

	form_data_dict = dict();
	form_data_dict["name"] = request.POST.get("name")
	form_data_dict["email"] = request.POST.get("email")
	form_data_dict["phone"] = request.POST.get("phone")
	form_data_dict["message"] = request.POST.get("message")

	data = dict()
	data['err'] = mainService(1).storeMessage(request)

	if bool(data['err'].get('success')) == False:
		data['postdata'] = form_data_dict

	return render(request, 'contact.html', data)

templates/blog.html
{% extends 'main.html' %}
{% load pg_extras_tag %}
{% load static %}
{% block menu %}
{% include "menus.html" with active_tab='blog' %}
{% endblock %}
{% block content %}
<!--=====================Content======================-->
<section class="content">
	<div class="container"><div class="ic">More Website Templates @ TemplateMonster.com - May 05, 2014!</div>
		<div class="row">
			<div class="grid_11">
				{% for blogInfo in blog%}
				<div class="blog">
					<time datetime='2014-01-01'>{% get_date blogInfo.created_date %}<span>{% get_month blogInfo.created_date %}</span></time>
					<img src="{{ blogInfo.image.url }}" alt="" class="img_inner fleft">
					<div class="extra_wrapper">
						<h3 class="blog_head color1"><a href="#">{{ blogInfo.title }}</a></h3>
						{{ blogInfo.desc|safe }}
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
</section>
{% endblock %}

templates/contact.html
{% extends 'main.html' %}
{% block menu %}
{% include "menus.html" with active_tab='contact' %}
{% endblock %}
{% load pg_extras_tag %}
{% block content %}
<!--=====================Content======================-->
<section class="content">
	<div class="container"><div class="ic">More Website Templates @ TemplateMonster.com - May 05, 2014!</div>
		<div class="row">
			<div class="grid_12">
				{% load_error_box err.success %}
				<div class="map">
					<figure>
						<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d24214.807650104907!2d-73.94846048422478!3d40.65521573400813!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sus!4v1395650655094" style="border:0"></iframe>
					</figure>
				</div>
			</div>
			<div class="clear"></div>
			<div class="grid_5">
				<h3>Contact Info</h3>
				<p>24/7 support is on for all <span class="color1"><a href="http://www.templatemonster.com/website-templates.php" rel="nofollow">premium designs</a></span> of TemplateMonster. Free templates go without it.</p>
				<p>Need help in customization? Ask guys from <span class="color1"><a href="http://www.templatetuning.com/" rel="nofollow">TemplateTuning</a></span>.</p>
				The Company Name Inc. <br>
				9870 St Vincent Place,<br>
				Glasgow, DC 45 Fr 45.<br>
				Telephone: +1 800 603 6035<br>
				FAX: +1 800 889 9898<br>
				E-mail: <a href="#">mail@demolink.org</a>
			</div>
			<div class="grid_6 preffix_1">
				<h3>Contact Form</h3>
				<form id="form" method="POST" action="{% url 'pg:contact' %}">
					{% csrf_token %}
					<label class="name">
						<input type="text" name="name" placeholder="Name:" data-constraints="@Required @JustLetters" value="{{ postdata.name }}" />
						{% load_error_box err.name %}
					</label>
					<label class="email">
						<input type="text" name="email" placeholder="E-mail:" data-constraints="@Required @Email" value="{{ postdata.email }}" />
						{% load_error_box err.email %}
					</label>
					<label class="phone">
						<input type="text" name="phone" placeholder="Phone:" data-constraints="@Required @JustNumbers" value="{{ postdata.phone }}" />
						{% load_error_box err.phone %}
					</label>
					<label class="message">
						<textarea name="message" placeholder="Message:" data-constraints='@Required @Length(min=20,max=999999)'>{{ postdata.message }}</textarea>
						{% load_error_box err.message %}
					</label>
					<div>
						<div class="clear"></div>
						<div class="btns">
							<a href="{% url 'pg:contact' %}" data-type="reset" class="btn bt__2">Clear</a>
							<button data-type="submit" class="btn bt__2">Submit</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</section>
{% endblock %}

templates/home.html
{% extends 'main.html' %}
{% load static %}
{% block menu %}
{% include "menus.html" with active_tab='home' %}
{% endblock %}
{% block content %}
<div class="slider_wrapper">
	<div id="camera_wrap" class="">
		{% for bannerInfo in banner %}
		<div data-src="{{ bannerInfo.image.url }}">
			<div class="caption fadeIn">
				<div class="title">{{ bannerInfo.title }}</div>
				{{ bannerInfo.desc|safe }}
			</div>
		</div>
		{% endfor %}
	</div>
</div>
<!--=====================Content======================-->
<div class="block1">
	<div class="container">
		<div class="row">
			<div class="grid_12">
				<div class="rel">
					<p>
					Hi! I’m Katrine Dove. Photography is a passion of mine. Let me use my talent & professionalism to capture the precious moments of your life.
					</p>
					<a href="#" class="btn bt__1">Hire Me</a>
				</div>
			</div>
		</div>
	</div>
</div>
<section class="content">
	<div class="container"><div class="ic">More Website Templates @ TemplateMonster.com - May 05, 2014!</div>
		<div class="row">
			<div class="grid_12">
				<h2>Portfolio</h2>
				<div class="gallery">
					<div class="row">
						{% for catInfo in category%}
						<div class="grid_4">
							<a href="{{ catInfo.image.url }}" class="gal_item">
								<img src="{{ catInfo.image.url }}" alt="">
								<div class="gal_caption">{{ catInfo.title }}</div>
								<span class="gal_magnify"></span>
							</a>
						</div>
						{% endfor %}
					</div>
				</div>
			</div>
			<div class="clear"></div>
			<div class="grid_4">
				<h3 class="mb__0">Equipment</h3>
				<div class="block2">
					<div class="block2_title color1">Camera</div>
						<ul class="list">
						<li><a href="#">Lorem ipsum dolorertolo </a></li>
						<li><a href="#">Git met consecteturert </a></li>
						<li><a href="#">Odipiscing elit mollis erat</a></li>
					</ul>
				</div>
				<div class="block2">
					<div class="block2_title color1">Lighting</div>
					<ul class="list">
						<li><a href="#">Lorem ipsum dolorilomo </a></li>
						<li><a href="#">Aconsectetur teroloter </a></li>
						<li><a href="#">Sdipiscing elitmollis erat </a></li>
					</ul>
				</div>
			</div>
			<div class="grid_4">
				<h3>About me</h3>
				<p>Need more information about this thingummy? Follow the <span class="color1"><a href="http://blog.templatemonster.com/free-website-templates/" rel="nofollow">link</a></span>.</p>
				<p>Choose <span class="color1"><a href="http://www.templatemonster.com/properties/topic/design-photography/" rel="nofollow">designs</a></span> of this kind at TemplateMonster’s website.</p>
				Cras facilisis, nulla vel viverra auctor, leo magna sodales felis, quis malesuada nibh odio ut velit. Proin pharetra luctus diam, a scelerisque eros convallis accumsanInteger convallis orci vel mi laoreet, at ornare lorem consequatasellus erat nisl<br>
				<a href="#" class="btn bt__2">Read More</a>
			</div>
			<div class="grid_4">
				<h3>Publications</h3>
				<ul class="list1">
					<li>
						<div class="list_count">1</div>
						<div class="extra_wrapper">
							<div class="list1_title color2"><a href="#">“Lorem ipsum dolor sit met </a></div>In mollis erat mattis neque facilisis, sit amet ultricies erat rutrumras
							<a href="#" class="color1 td_und">More</a>
						</div>
					</li>
					<li>
						<div class="list_count">2</div>
						<div class="extra_wrapper">
							<div class="list1_title color2"><a href="#">“Dorem ipsum dolor sit met </a></div>In mollis erat mattis neque facilisis, sit amet ultricies erat rutrumras
							<a href="#" class="color1 td_und">More</a>
						</div>
					</li>
					<li>
						<div class="list_count">3</div>
						<div class="extra_wrapper">
							<div class="list1_title color2"><a href="#">“Kerem ipsum dolor sit met </a></div>In mollis erat mattis neque facilisis, sit amet ultricies erat rutrumras
							<a href="#" class="color1 td_und">More</a>
						</div>
					</li>
				</ul>
			</div>
			<div class="clear"></div>
			<div class="grid_12">
				<h3 class="head1">Multimedia</h3>
			</div>
			<div class="clear"></div>
		</div>
	</div>
	<div id="owl">
		{% for ranInfo in random %}
		<div class="item"><img src="{{ ranInfo.image.url }}" alt=""></div>
		{% endfor %}
	</div>
</section>
{% endblock %}

templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Portfolio</title>
		<meta charset="utf-8">
		<meta name="format-detection" content="telephone=no">
		<link rel="icon" href="{% static 'images/favicon.ico' %}">
		<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
		<link rel="stylesheet" href="{% static 'css/stuck.css' %}">
		<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
		<link rel="stylesheet" href="{% static 'css/form.css' %}">
		<link rel="stylesheet" href="{% static 'css/touchTouch.css' %}">
		<link rel="stylesheet" href="{% static 'css/camera.css' %}">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
		<script src="{% static 'js/jquery.js' %}"></script>
		<script src="{% static 'js/jquery-migrate-1.1.1.js' %}"></script>
		<script src="{% static 'js/script.js' %}"></script>
		<script src="{% static 'js/superfish.js' %}"></script>
		<script src="{% static 'js/jquery.equalheights.js' %}"></script>
		<script src="{% static 'js/jquery.mobilemenu.js' %}"></script>
		<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
		<script src="{% static 'js/tmStickUp.js' %}"></script>
		<script src="{% static 'js/jquery.ui.totop.js' %}"></script>
		<script src="{% static 'js/touchTouch.jquery.js' %}"></script>
		<script src="{% static 'js/owl.carousel.js' %}"></script>
		<script src="{% static 'js/sForm.js' %}"></script>
		<script src="{% static 'js/camera.js' %}"></script>
		<!--[if (gt IE 9)|!(IE)]><!-->
		<script src="{% static 'js/jquery.mobile.customized.min.js' %}"></script>
		<!--<![endif]-->
		<script>
		$(document).ready(function(){
			jQuery('#camera_wrap').camera({
				loader: false,
				pagination: false ,
				minHeight: '200',
				thumbnails: false,
				height: '39,0625%',
				caption: true,
				navigation: true,
				fx: 'mosaic'
			});
			var owl = $("#owl");
			owl.owlCarousel({
				items : 7, //10 items above 1000px browser width
				itemsDesktop : [995,5], //5 items between 1000px and 901px
				itemsDesktopSmall : [767, 3], // betweem 900px and 601px
				itemsTablet: [700, 3], //2 items between 600 and 0
				itemsMobile : [479, 2], // itemsMobile disabled - inherit from itemsTablet option
				navigation : true,
			});
			$().UItoTop({ easingType: 'easeOutQuart' });
			$('#stuck_container').tmStickUp({});
			$('.gallery a.gal_item').touchTouch();
		});
		</script>
		<!--[if lt IE 8]>
		<div style=' clear: both; text-align:center; position: relative;'>
			<a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
				<img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
			</a>
		</div>
		<![endif]-->
		<!--[if lt IE 9]>
			<script src="js/html5shiv.js"></script>
			<link rel="stylesheet" media="screen" href="css/ie.css">
		<![endif]-->
	</head>
	<body class="" id="top">
<!--==============================header=================================-->
		<header>
			<div id="stuck_container">
				<div class="container">
					<div class="row">
						<div class="grid_12">
							<h1>
								<a href="index.html">
									<img src="{% static 'images/logo.png' %}" alt="Your Happy Family">
								</a>
							</h1>
							<div class="menu_block ">
								<nav class="horizontal-nav full-width horizontalNav-notprocessed">
									{% block menu %}Menu Content{% endblock %}
								</nav>
								<div class="clear"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</header>
		<div class="main">
			<!--=====================Content======================-->
			{% block content %}Body Content{% endblock %}

			<!--==============================Bot_block=================================-->
			<section class="bottom_block">
				<div class="container">
					<div class="row">
						<div class="grid_5">
							<div class="bot_title">
								<span class="fa fa-envelope-o"></span>Subscribe to My Newsletter
							</div>
						</div>
						<div class="grid_7">
							<form id="newsletter">
								<div class="row">
									<div class="grid_4">
										<div class="rel">
											<div class="success">Your subscrsibe request has been sent!</div>
											<label class="email">
												<input type="email" value="Your Email Address Here" >
												<span class="error">*This is not a valid email address.</span>
												<span class="clear"></span>
											</label>
										</div>
									</div>
									<div class="grid_3">
										<a href="#" class="btn bt__2" data-type="submit">Submit</a>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</section>
		</div>
		<!--==============================footer=================================-->
		<footer>
			<div class="container">
				<div class="row">
					<div class="grid_12">
						<div class="footer_socials">
							<a href="#" class="fa fa-twitter"></a>
							<a href="#" class="fa fa-facebook"></a>
							<a href="#" class="fa fa-google-plus"></a>
							<a href="#" class="fa fa-pinterest"></a>
						</div>
						<div class="copy">
							<span class="brand">KatrineDove</span> &copy; <span id="copyright-year"></span> | <a href="#">Privacy Policy</a>
							<div class="sub_copy">
								Website designed by <a href="http://www.templatemonster.com/" rel="nofollow">TemplateMonster.com</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</footer>
	</body>
</html>

templates/menus.html
<ul class="sf-menu">
	<li class="{% if active_tab == 'home' %}current{% endif %}"><a href="{% url 'pg:home' %}">About</a></li>
	<li class="{% if active_tab == 'portfolio' %}current{% endif %}"><a href="{% url 'pg:portfolio' %}">Portfolio</a></li>
	<li class="{% if active_tab == 'resume' %}current{% endif %}"><a href="{% url 'pg:resume' %}">Resume</a></li>
	<li class="{% if active_tab == 'blog' %}current{% endif %}"><a href="{% url 'pg:blog' %}">Blog</a></li>
	<li class="{% if active_tab == 'contact' %}current{% endif %}"><a href="{% url 'pg:contact' %}">Contacts</a></li>
</ul>

templates/portfolio.html
{% extends 'main.html' %}
{% load pg_extras_tag %}
{% load static %}
{% block menu %}
{% include "menus.html" with active_tab='portfolio' %}
{% endblock %}
{% block content %}
<!--=====================Content======================-->
<section class="content cont_pad1">
	<div class="container"><div class="ic">More Website Templates @ TemplateMonster.com - May 05, 2014!</div>
		<div class="gallery gall__1">
			<div class="row">
			{% for cat_id, map_result in portfolio.port_info.items %}
				<div class="grid_4">
					<h3>{{ portfolio.cat_info|get_item:cat_id }}</h3>
				</div>
				<div class="clear"></div>
				{% for port_id, port in map_result.items %}
				<div class="grid_4">
					<a href="{{ port.image.url }}" class="gal_item">
						<img src="{{ port.image.url }}" alt="">
						<div class="gal_caption">
							<time datetime="2014-01-01">{% get_day_month_year port.created_date %}</time>
						</div>
						<span class="gal_magnify"></span>
					</a>
				</div>
				{% endfor %}
			{% endfor %}
			</div>
		</div>
	</div>
</section>
{% endblock %}

templates/resume.html
{% extends 'main.html' %}
{% block menu %}
{% include "menus.html" with active_tab='resume' %}
{% endblock %}
{% block content %}
<section class="content cont__1">
	<div class="container"><div class="ic">More Website Templates @ TemplateMonster.com - May 05, 2014!</div>
		<div class="row">
			<div class="grid_4">
				<h3>Education</h3>
			</div>
			<div class="clear"></div>
			<div class="grid_4">
				<p>Cras facilisis, nulla vel viverra auctor, leo magna sodales felis, quis malesuada nibh odio ut velit. Proin pharetra luctus diam, a scelerisque eros convallis accumsanInteger convallis orci vel mi laoreet, at ornare lorem consequatasellus erat nisl auctor vel velit sed,pharetra venenatis nulla. </p>
				Vestibulum volutpat turpis ut massa commodo, quis aliquam massa facilisis. Donec non sapien a erat porttitor aliquet.
			</div>
			<div class="grid_5 preffix_1">
				<ul class="list2">
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Mark Johnson</a></div>
							<div class="grid_3">Aenean nonummy hendrerit mauris</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Emma Grosh</a></div>
							<div class="grid_3">Cum sociis natoque penatibus et mag</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Patrick Pool</a></div>
							<div class="grid_3">Nulla dui. Fusce feugiat malesu</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: John McCoist </a></div>
							<div class="grid_3">Morbi nunc odio gravida at</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Jessica Priston</a></div>
							<div class="grid_3">Maecenas tristique orci ac sem</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Sam Kromstain</a></div>
							<div class="grid_3">Duis ultricies pharetra magna</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Alan Smith</a></div>
							<div class="grid_3">Lorem ipsum dolor sit amet</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: John Franklin</a></div>
							<div class="grid_3">Consectetuer adipiscing elit</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Anton Stegner</a></div>
							<div class="grid_3">Mauris fermentum dictum magn</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Mike Tompson</a></div>
							<div class="grid_3">Sed laoreet aliquam leo</div>
						</div>
					</li>
				</ul>
			</div>
			<div class="clear"></div>
			<div class="grid_4">
				<h3 class="head1">Commercials</h3>
			</div>
			<div class="clear"></div>
			<div class="grid_4">
				<p>Dras facilisis, nulla vel viverra auctor, leo magna sodales felis, quis malesuada nibh odio ut velit. Proin pharetra luctus diam, a scelerisque eros convallis accumsanInteger convallis orci vel mi laoreet, at ornare lorem consequatasellus erat nisl auctor vel velit sed,pharetra venenatis nulla. </p>
				Vestibulum volutpat turpis ut massa commodo, quis aliquam massa facilisis. Donec non sapien a erat porttitor aliqueter.
			</div>
			<div class="grid_5 preffix_1">
				<ul class="list2">
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: John McCoist </a></div>
							<div class="grid_3">Nenean nonummy hendrerit mauris</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Jessica Priston</a></div>
							<div class="grid_3">Cum sociis natoque penatibus et mag</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Sam Kromstain</a></div>
							<div class="grid_3">Nulla dui. Fusce feugiat malesu</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Alan Smith</a></div>
							<div class="grid_3">Morbi nunc odio gravida at</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: John Franklin</a></div>
							<div class="grid_3">Maecenas tristique orci ac sem</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Anton Stegner</a></div>
							<div class="grid_3">Duis ultricies pharetra magna</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Mike Tompson</a></div>
							<div class="grid_3">Lorem ipsum dolor sit amet</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Din Haddon</a></div>
							<div class="grid_3">Consectetuer adipiscing elit</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Mark Johnson</a></div>
							<div class="grid_3">Mauris fermentum dictum magn</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Mark Johnson</a></div>
							<div class="grid_3">Sed laoreet aliquam leomer</div>
						</div>
					</li>
				</ul>
			</div>
			<div class="clear"></div>
			<div class="grid_4">
				<h3 class="head1">Music Videos</h3>
			</div>
			<div class="clear"></div>
			<div class="grid_4">
				<p>Oras facilisis, nulla vel viverra auctor, leo magna sodales felis, quis malesuada nibh odio ut velit. Proin pharetra luctus diam, a scelerisque eros convallis accumsanInteger convallis orci vel mi laoreet, at ornare lorem consequatasellus erat nisl auctor vel velit sed,pharetra venenatis nullare. </p>
				Mestibulum volutpat turpis ut massa commodo, quis aliquam massa facilisis. Donec non sapien a erat porttitor aliquety.
			</div>
			<div class="grid_5 preffix_1">
				<ul class="list2">
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Sam Kromstain</a></div>
							<div class="grid_3">Hoenean nonummy hendrerit mauris</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Alan Smith</a></div>
							<div class="grid_3">Cum sociis natoque penatibus et mag</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: John Franklin</a></div>
							<div class="grid_3">Nulla dui. Fusce feugiat malesu</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Anton Stegner</a></div>
							<div class="grid_3">Morbi nunc odio gravida at</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Mike Tompson</a></div>
							<div class="grid_3">Maecenas tristique orci ac sem</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Din Haddon</a></div>
							<div class="grid_3">Duis ultricies pharetra magna</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Mark Johnson</a></div>
							<div class="grid_3">Lorem ipsum dolor sit amet</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Mark Johnson</a></div>
							<div class="grid_3">Consectetuer adipiscing elit</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Emma Grosh</a></div>
							<div class="grid_3">Mauris fermentum dictum magn</div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="grid_2"><a href="#">Dir: Patrick Pool</a></div>
							<div class="grid_3">Sed laoreet aliquam leom</div>
						</div>
					</li>
				</ul>
			</div>
		</div>
	</div>
</section>
{% endblock %}